apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: oowh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oowh
    app.kubernetes.io/part-of: byoc-app-ooie
  name: oowh4j6k
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: oowh
    weight: null
status: {}
