apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: oowh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oowh
    app.kubernetes.io/part-of: byoc-app-ooie
  name: oowh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: oowh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: oowh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-zmup-tenant/byoc-app-ooie/oowh@sha256:691a661e6252ff71112f9a6a45073e26bd6d7194c1cb2877e3ba83b9b3bb31ca
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
